# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-OWL
version:      0.0.4
version_from: lib/Class/OWL.pm
installdirs:  site
requires:
    Class::MOP:                    0
    Test::More:                    0
    version:                       0
    XML::CommonNS:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
